# https://docs.travis-ci.com/user/languages/cpp/
language: cpp

# https://docs.travis-ci.com/user/docker/
services:
- docker

before_install:
- docker info
- docker build -t crystalnet .

script:
# The default is
# - ./configure && make && make test
- docker run -it crystalnet make test
